#!/bin/bash
# /etc/init.d/surveillance

### BEGIN INIT INFO
# Provides:          surveillance
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage a servo
### END INIT INFO


case "$1" in 
    start)
        echo "Starting surveillance"
	
	source /home/pi/.profile
	workon cv
	cd /home/pi/home_surveillance
	python pi_surveillance.py --conf conf.json &

        ;;
    stop)
        echo "Stopping surveillance"
	pkill -f pi_surveillance.py
	killall surveillance
	;;
    *)
        echo "Usage: /etc/init.d/surveillance start|stop"
        exit 1
        ;;
esac

exit 0
